version: "3"
services:
  client:
    container_name: client-react
    build:
      dockerfile: ./docker/client.Dockerfile
      context: .
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    networks:
      - test-network
    environment:
      - CHOKIDAR_USEPOLLING=true

  node:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    container_name: server
    volumes:
      - ./server:/usr/app
    ports:
      - 3002:3002
    networks:
      - test-network

  db:
    build:
      dockerfile: ./docker/db.Dockerfile
      context: .
    restart: always
    ports:
      - 5432:5432
    networks:
      - test-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql

  pgadmin:
    build:
      dockerfile: ./docker/pgadmin.Dockerfile
      context: .
    container_name: mpg
    restart: always

    ports:
      - 82:80
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
